version: '2'

services:
  stock_db:
    restart: always
    image: postgres
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=passw0rd    
    expose:
      - "5432"
    ports:
      - "54321:5432"

  exchange_matching:
    build: ./src
    command: ./exchange_matching
    volumes:
      - ./src:/code
    expose:
      - "12345"
    ports:
      - "12345:12345"
    depends_on:
      - stock_db
